### PR TITLE
docs: 0.19 changelog

### PR DESCRIPTION
**Pull request by Jorropo**
This is mostly the only "big" user facing changes except resource manager, the rest is background work.

### CODE REVIEW

**Comment by lidel** [comment]
Added Gateway section with IPIP-351 changes – https://github.com/ipfs/kubo/pull/9707/commits/fb663c6bb474a998bc4c0f56ef7c48dbe6c289e9.

We also did https://github.com/ipfs/go-libipfs/pull/155, https://github.com/ipfs/go-libipfs/pull/150 and https://github.com/ipfs/go-libipfs/pull/187 but I feel these are low-level changes that end user is not interested about. Lmk if we should add a sentence about these.

**Review by hacdias — APPROVED** [review]

**Review by BigLep — APPROVED** [review]
Thanks for the additions @lidel .  They look good to me.

@Jorropo : I think you an merge once you've confirmed whether we aren't being redundant on "PubSub message caching improvements".

Updates also slipped in for https://github.com/ipfs/kubo/pull/9708

**Comment by BigLep** [comment]
@Jorropo: can you please get this resolved and merged?  Please confirm whether the pubsub comments are needed per https://github.com/ipfs/kubo/pull/9707#pullrequestreview-1332844167

**Comment by galargh** [comment]
I'm merging this as-is. Please feel free to update the changelog later.

**Pull request merged**
