### PR TITLE
fix(gateway): undesired conversions to dag-json and friends

### PR DESCRIPTION
**Pull request by hacdias**
In the spirit of https://github.com/protocol/bifrost-infra/issues/2290 and https://github.com/ipfs/specs/pull/328#pullrequestreview-1254267132, this PR removes implicit conversion from UnixFS/RAW to DAG-* when `json` is requested, and performs the conversion only when expliti `dag-json`  is present in the request.

We also fixed handling of CID with `json` and `cbor` codecs + added more tests.

Weird, unrelated things, are happening in the CI. – tracked in https://github.com/ipfs/kubo/pull/9570

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel another option I see is to completely remove support for `?format=json|cbor` but that will also raise the question of: should we then also support CIDs whose codec is JSON|CBOR?

**Comment by lidel** [comment]
Let's keep support for CIDs with `json` and `cbor`codec: when someone requests  `/ipfs/bagaaierayeva7pcl4bchk3udf3i5qm3eeqlbj6tzcmidv64uonglmi5nebca` without any parameters, we want gateway to return same payload as raw block response, but with  `content-type` based on the codec from CID.

**Comment by hacdias** [comment]
@lidel we had the tests already 😃

**Comment by lidel** [comment]
I am writing more tests, and they found more issues

- Requesting CID with  `json` codec  with `Accept: aplication/json` should work, but does not (+cbor variant)
- Requesting CID with  `dag-json` codec as `application/json` should work, but does not (+cbor variant)

**Comment by lidel** [comment]
Pushed two fixes and tests in https://github.com/ipfs/kubo/pull/9566/commits/c3ebe80d585af0091b506ffd3103de3f5b28f770
It should solve the problem from https://github.com/protocol/bifrost-infra/issues/2290 and be ready for 0.18.

@hacdias when you start on Friday, take a look at the above changes as a sanity check and lmk if anything is weird or needs to be better commented. 

(interop/webui tests are failing due to unrelated reason – tracking in https://github.com/ipfs/kubo/pull/9570)

**Comment by hacdias** [comment]
@lidel what you pushed works if a file has JSON content (or whatever content it has). However, it does not work for a CID that has the codec JSON (or CBOR for that matter). The fault in the tests lies in that `FILE_JSON_CID` is just a regular UnixFS/Raw CID and not a JSON CID.

I pushed a fix and another test... I'm also not very happy with this. It's becoming increasingly complex and I feel like there __must__ be a way of simplifying this. I will give it some thought during today's morning and see if I can simplify it somehow.

**Comment by lidel** [comment]
Thanks for catching this. 

Maybe we could simplify things a bit by adding CID codec check at the end of [`customResponseFormat` func](https://github.com/ipfs/kubo/blob/fb616814939e63d200f9c0c15166e688996a25a5/core/corehttp/gateway_handler.go#L870), and set explicit one when CID is `json` `cbor` `dag-json` or `dag-cbor`? at least that will happen it one place

**Comment by hacdias** [comment]
@lidel I think we should merge as-is and simplify later if possible.

**Comment by BigLep** [comment]
I'm good with us doing the followups in the next release (assuming we do the changelog update and have the followup issue for 0.19).  Thanks for handling.

**Comment by lidel** [comment]
I am writing updates to release notes section, will push and merge before Monday.

**Review by lidel — APPROVED** [review]

**Pull request merged**
