### PR TITLE
feat(gateway): update gateway api, no multi-range support

### PR DESCRIPTION
**Pull request by hacdias**
Requires:

- [x] https://github.com/ipfs/boxo/pull/369
- [x] Removed `TestGatewayMultiRange`
- [x] Have updated conformance tests running https://github.com/ipfs/gateway-conformance/pull/113

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]

**Comment by lidel** [comment]
Pushed https://github.com/ipfs/kubo/pull/10024/commits/ae6b1136da8a78d4c4dc80288500a35862fa6cc2 with pinned conformance CI revision to double-check if unreleased 404 tests from   ipfs/gateway-conformance#131 and ipfs/gateway-conformance#132 pass against this PR. 
(Would be unfortunate if we realize 404s are broken after this PR is merged)

Will check result tomorrow.

**Comment by hacdias** [comment]
@lidel seem to pass 😄

**Review by lidel — CHANGES_REQUESTED** [review]
### Slight concern on user data loss caused by CAR root change

Someone probably built things that depend on exporting CAR from gateway and then importing it to Kubo. 

By removing the CAR root we introduce a surface for data loss, as exported full DAG is no longer pinned by default on `ipfs dag import.

We should double check if we change default behavior or not, and document what changed:

- [x] see if we  keep useful root when we know it: https://github.com/ipfs/boxo/pull/369#discussion_r1290093622
- [ ] add/update changelog for Kubo 0.23.md and note when CAR responses no longer have a meaningful root explicitly listed in CARv1, but use bogus `bafkqaaa` as a placeholder (4XX/5XX errors only, or more?)

**Comment by hacdias** [comment]
@lidel 

>  see if we keep useful root when we know

Please check my comment on that thread.

> add/update changelog for Kubo 0.23.md and note when CAR responses no longer have a meaningful root explicitly listed in CARv1, but use bogus bafkqaaa as a placeholder (4XX/5XX errors only, or more?)

I added the information about what to expect.

**Pull request merged**
