### PR TITLE
docs: fix typo [skip changelog]

### PR DESCRIPTION
**Pull request by patrickReiis**
Changed "out" to "our".

### CODE REVIEW

**Review by hacdias — APPROVED** [review]

**Comment by patrickReiis** [comment]
Hi @hacdias , I don't understand why the "Go Test / go-test (pull_request)"  failed, will this pull request be merged automatically? Thanks.

**Comment by patrickReiis** [comment]
Hi @hacdias , can you run the tests again? Thanks.

**Comment by patrickReiis** [comment]
Hi @lidel can you take a look? Thanks.

**Comment by patrickReiis** [comment]
Oh gosh I ruined everything. I was going to keep studying the source code and through the Github UI I clicked to update my fork, I did this without really thinking and then what happened was that a useless "merge commit" was created. So I had to rebase my master branch and force push it so I could get rid of the merge commit. The problem is that now the last commit says I committed and @lidel  authored which isn't the case. I learned my lesson, always stay calm when it comes to pull requests and don't let anxiety control what I do.

**Comment by hacdias** [comment]
Hey @patrickReiis! Thanks for the typo fix. I rebased the PR for you and re-runned the tests. I will merge it. If you want to contribute more meaningfully, I would look at issues tagged with ["Help Wanted"](https://github.com/ipfs/kubo/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). Each issue also has a difficulty tag attached, so if you want to make more contributions, I would start there.

**Pull request merged**
