### PR TITLE
feat: Add commandline completion for the Fish shell

### LINKED ISSUE #8770: Fish Autocompletion for IPFS CLI
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Currently, only `bash` is supported for CLI completions. It'd be great to have this functionality extended to the `fish` shell, (and `zsh` too, if needed).

### PR DESCRIPTION
**Pull request by anka-213**
Also shows descriptions of flags and commands when autocompleting

There are some edge-cases where it doesn't behave as expected (e.g. if an option with an argument is used before a subcommand), but overall it seems to work well

Fixes #8770

Use it with e.g.
```
ipfs commands completion fish | source
```

### CODE REVIEW

**Comment by anka-213** [comment]
I'm not sure how best to add tests for this change, since we probably (?) don't want to install fish in the test environment. It's not a critical feature and it doesn't seem like something that's likely to break, so maybe it's fine to not test it and just let users report it if something breaks? Or maybe just check that the completion generation doesn't crash, but not that it actually generates valid completion code?

**Comment by Jorropo** [comment]
> since we probably (?) don't want to install fish in the test environment

I don't see a problem doing this, it's messy already, you aren't gonna make it worst.

> Or maybe just check that the completion generation doesn't crash, but not that it actually generates valid completion code?

Yeah, at least exercise this codepath, if you can at least parse it with fish, that would be nice.

**Comment by anka-213** [comment]
@Jorropo  So how would I add fish to the test environment? I have added a test for the fish completions now.

**Comment by Jorropo** [comment]
@anka-213 thx for your patches.
I pushed them to #9376 to get CI to cooperate
And even installing fish it fails with:
```

expecting success: 
  fish -N -c "source completions.fish && complete -C \"ipfs ver\" | grep -q \"version.Show IPFS version information.\" "

fish: invalid option -- 'N'
not ok 2 - generated completions completes 'ipfs version'
#	
#	  fish -N -c "source completions.fish && complete -C \"ipfs ver\" | grep -q \"version.Show IPFS version information.\" "
#	
```
Could you please take a look ?

**Comment by anka-213** [comment]
@Jorropo The flag `-N` is short for `--no-config`, which was [introduced in `fish-3.3.0`](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#scripting-improvements-3) (latest is 3.6.0), but CI installed `fish-3.1.0`, so that's why it failed. You can just remove it, I just added it to reduce the risk of system config affecting the tests, but it's not important.

**Review by Jorropo — APPROVED** [review]
LGTM, I'm not sure the fish part is correct, but at worst someone can report about it.

Thx

**Comment by Jorropo** [comment]
Will merge in #9376

**Pull request closed without merging**
