### PR TITLE
feat: cmd/ipfs: Make it possible to depend on cmd/ipfs

### PR DESCRIPTION
**Pull request by magik6k**
Today there are two ways to run kubo with plugins, one on non-linux systems:
* Preload - which requires the plugin to be in the kubo repo, or at least requires manual build of kubo
* Use a Go plugin, which don't work on most systems, and won't work if any build dependency isn't perfectly aligned - which in practice makes them almost completely unusable for anything non-trivial

This PR adds a third way - by depending on `cmd/ipfs/kubo` it's now possible to depend on this repo to create kubo-derived nodes with user-specified plugins.

I needed this for RIBS, which is a highly-advanced blockstore, that couldn't justifiably "just be integrated" into upstream kubo.

* KuboRIBS `main` using this functionality: https://github.com/lotus-web3/ribs/blob/a8d8aff2953416bc267debd0ee05f591cca582d9/integrations/kuri/cmd/kuri/main.go#L16-L20
* Which loads [this](https://github.com/lotus-web3/ribs/blob/a8d8aff2953416bc267debd0ee05f591cca582d9/integrations/kuri/ribsplugin/kuboribs.go) plugin

Review probably easiest commit-by-commit.

### CODE REVIEW

**Comment by guseggert** [comment]
This looks like a much better way to inject plugins than the standard practice of modifying the preloads and rebuilding kubo bin. What are the drawbacks to this?

**Comment by BigLep** [comment]
@guseggert : maybe this is something you and @magik6k can discuss in person at IPFS Thing 2023?

**Comment by BigLep** [comment]
2023-05-18 maintainer conversation: all agreed this should get done for the next release.  We haven't assigned an owner yet.  A doc update should be made to https://github.com/ipfs/kubo/blob/master/docs/customizing.md as well.

**Comment by magik6k** [comment]
fyi the other branch - https://github.com/ipfs/kubo/compare/magiks-ribs-hacks - is now up to date with master. May make sense to swap this PR to that one

**Comment by Stebalien** [comment]
Replaced by https://github.com/ipfs/kubo/pull/10219.

**Pull request closed without merging**
