### PR TITLE
Badger2 integration

### PR DESCRIPTION
**Pull request by feld**
Supercedes #7705

### CODE REVIEW

**Comment by feld** [comment]
This is working for me so far and could use more testers. I haven't experimented with Badger 3 yet, but this should work for larger IPFS storage that needs reliable garbage collection as flatfs is at the mercy of your OS filesystem's ability to handle small files and your kernel's ability to handle the flood of syscalls...

**Comment by Jorropo** [comment]
@feld CI is not passing try running `go vet ./...` on your code.

**Comment by Zir0h** [comment]
Hi, having this would be super awesome!

**Comment by acejam** [comment]
It would be great to see this merged!

**Comment by CsterKuroi** [comment]
How about Badger2's GC performance

**Comment by feld** [comment]
> How about Badger2's GC performance

it's working for me, but definitely needs more testers

**Comment by dokterbob** [comment]
Soon(tm) we'll be bumping our kubo built at ipfs-search.com. Once that's gathered a bit of data, I could give this a spin and see what it does in production. ETA ~2 weeks.

**Comment by feld** [comment]
> Soon(tm) we'll be bumping our kubo built at ipfs-search.com. Once that's gathered a bit of data, I could give this a spin and see what it does in production. ETA ~2 weeks.

I actually think IPFS should be using LMBD / MDBX for storage instead of something like Badger as the default storage engine. I'm quite surprised nobody has gone down that rabbit hole yet.

https://github.com/torquem-ch/mdbx-go

https://twitter.com/deplinenoise/status/840453414546898944

And then if you need to scale REALLY big it should be some object storage backend like CEPH

maybe someone with more free time will pull on this thread for me

**Review by lidel — CHANGES_REQUESTED** [review]
Thank you for submitting this PR. 

Before one of Kubo maintainers reviews this, I need to ask two questions:
- Is Badger 2 supported upstream at all? IIUC the last time (~2020?)  we've reported [issues upstream](https://github.com/dgraph-io/badger/issues?q=is%3Aissue+ipfs)  they were closed and we were asked to upgrade to Badger 3 
- Is anyone maintaining badger _in general_? AFAK entire team left DGraph in January:  https://discuss.dgraph.io/t/quitting-dgraph-labs/16702 


Merging unsupported datastore is not something we want, so team is unlikely to invest time in reviewing this until we have confidence this won't become dead on arrival.
Hope you understand our hesitance.


> I actually think IPFS should be using MDBX instead of something like Badger as the default storage engine

Looking at alternatives to badger that are actively maintained sounds sensible. Mind opening a dedicated issue for discussing this? (ideally with working code and benchmarks that show which workloads would benefit from it over flatfs, but a stub issue with links you provided is ok too).

Let's keep this PR about Badger 2.

**Comment by Jorropo** [comment]
@hsanjuan started work on badger3: https://github.com/ipfs/go-ds-badger3/ which sounds better than 2.
I join @lidel and @guseggert on their comments.

Filecoin also made work on datastores, what would be awesome is some testsuite that accepts a datastore interface and benchmark all of the features (we might actually have code for this somewhere, probably on the filecoin side).

But given than neither of them (badger 2 or 3) is maintained  I don't think we will be adding them, this is easy to ship as a plugin.

**Comment by hsanjuan** [comment]
Note badger3 is mantained, they had a release some weeks ago: https://github.com/dgraph-io/badger/releases

Unfortunately I don't think the "come back with benchmarks" is a useful approach.

Badger is optimized for SSDs. Both Badger and Pebble have lots of options that control many performance factors depending on things like available memory, need for compression etc. One big problem in Kubo is that badger options cannot be tuned, and defaults are specially bad for larger scale (they work on a 1GB raspberry pi though).

The underlying filesystem also matters, and the disk layout too (some datastores may work better with layouts in which writes are sharded across disks etc). In the case of flatfs, it is generally very slow, specially with ext4, but faster with XFS. Some datastores could be optimized for spinning disks, rather tan SSDs.

What benchmarks show is that badger cannot be used at scale (I mean, don't need a benchmark for that). Node restarts takes multiple minutes at certain scales. Also compaction don't work well at all in Badger v1, which means a lot of disk usage overhead. But perhaps badger3 with the right tuning works much much better, and perhaps Pebble even more.

Another issue is that Blockstore introduces caching and bloomfilter layers, but Badger3/Pebble already include those, so they would probably be doing things even worse.

Ultimately, things depend a lot on usage patterns (read vs writes, total amount of blocks, block-sizes etc). Badger v3 includes everything under 1MB in the LSM tree (memory) by default. That means someone using 1MB ipfs blocks is going to get a completely different behaviour than someone using 256KB blocks. Even worse, badgerv1 used 32 byes for this, which means even small things like CIDs go into disk.

What I mean is that the only way of making Kubo-storage not suck right now (it is really at a very bad place) is to add support for additional stores (badger3, pebble, potentially bolt), along with control of all configuration values, so that people can actually test different configurations. Whether that's via plugins or core support is up to you, but it is very low hanging fruit to just "pass".

---

> https://github.com/guseggert/go-ds-grpc

This is a nice experiment, but the network/serialization overhead here would kill performance. Some use-cases may not mind, but definitely not for heavy use like other backends could provide. I would add it nevertheless as it allows remote backends etc.

--- 

On another note, there is also not-so-low-hanging fruit: blockstore implementations like https://github.com/ipld/go-storethehash, sqlite-backed storage ala https://github.com/whyrusleeping/whypfs with refcounting etc. these do require time and more refactoring.

**Comment by Jorropo** [comment]
@hsanjuan thx for your answer,

---

> Note badger3 is mantained, they had a release some weeks ago: https://github.com/dgraph-io/badger/releases

I've jumped to conclusion too quickly, but looking at the releases it seems quite light:

Nov 4:
> Fixed
> - fix(manifest): fix manifest corruption due to race condition in concurrent compactions (https://github.com/dgraph-io/badger/pull/1756)
> - Chores
>  -Add CI/CD jobs to release branch
> - Add PR and Issue templates to release branch
> - Update Codeowners in release branch
> - Update Readme in release branch

Oct 15:
> fix(arm64): bump ristretto v0.1.0 --> v0.1.1 (https://github.com/dgraph-io/badger/pull/1806)

Looking at the code frequency we can see a clear shutdown early 2021: https://github.com/dgraph-io/badger/graphs/code-frequency

The project being maintained isn't a key point (we use badger1 after all), but AFAIT this isn't a project we can add now and iron later, so we should be more carefull when adding it.

---

> Unfortunately I don't think the "come back with benchmarks" is a useful approach.

My understanding is that for now badger2 and badger3 datastores are experiments / toes in the water, I hope that we (Kubo maintainers) don't need to get pulled in for this kind of work.
If it is hard for people to run their own fork or add plugins, this is a thing I would like to fix.

---

> What I mean is that the only way of making Kubo-storage not suck right now (it is really at a very bad place) is to add support for additional stores (badger3, pebble, potentially bolt), along with control of all configuration values, so that people can actually test different configurations. Whether that's via plugins or core support is up to you, but it is very low hanging fruit to just "pass".

This sounds awesome, but I think this shouldn't involve us. (see point above)

---

On an other note, we don't have any good visibility on how bad the issue is, I mean I know I'm using Kubo every days, but flatfs and badger are fine enough for my hundreds of GiBs workflow on my machine with too much ram, I know there is work in different places mainly around supporting bigger sizes, but I havn't been able to find an issue summering the issue, if you know of one or some other docs it would be nice so I could raise this at out triage meetings and we could place it on our board of priorities.

**Comment by hsanjuan** [comment]
@Jorropo you mean Kubo maintainers should not be involved in doing benchmarking or something else? 

> this is a thing I would like to fix.

How, whats on your mind?

---

Note that benchmarking was done early on Lotus development and that's how Badger2 was chosen for Lotus. Badger2 handles huge datastores there. Even if badger is no longer heavily maintained, that doesn't mean it is bad more many use-cases (better GC is what many people complain about and that should be way better in Badger3). Pebble is a more open question, as it is heavily maintained so it probably has improved since it was tried out. Unfortunately the benchmarks done back then (2 years ago) may have little meaning now, given how codebases and hardware improve etc.

@ajnavarro has some recent benchmarks that can give an idea of how things are today, but in the end I think it all depends on usecases.

**Pull request closed without merging**
