### PR TITLE
feat: gateway support for tar.gz

### PR DESCRIPTION
**Pull request by hacdias**
Built on top of #9029 and adds `tar.gz` format.

The official MIME Type for `.gz` is [`application/gzip`](https://www.iana.org/assignments/media-types/application/gzip). However, that makes it harder for us to distinguish what type of file it is. Therefore, I appended `+gzip` to the MIME Type of the TAR.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by Jorropo** [comment]
I don't like that such CPU hogging feature (file compression) is accessible on the gateway using the default config.

I would like this more if it was dynamically scaling the compression level based on the CPU load.
But I feel like this is asking for a lot.

**Comment by Jorropo** [comment]
Also if someone cared about that, I think they are running a gateway seriously, and if they are, they are using a reverse proxy for TLS.

Can't they just configure the reverse proxy to handle compression ?

**Comment by hacdias** [comment]
That's a valid point @Jorropo! However, this gateway feature is also available via the public API, e.g.:

```
https://gateway.ipfs.io/api/v0/get?arg=QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG&compression=true&archive=true
```

I don't mind keeping #9029 only. Also, please check #7746 for more context about this feature.

**Comment by Jorropo** [comment]
`api/v0` :disappointed: 

I don't mind if it's there but I think it should be optional. (I guess that a comment for the spec PR.)

Also I think it should be generalised.
If this gets in, there is no reason to not compress cars too. (but that a comment for opening a new issue)

**Review by lidel — CHANGES_REQUESTED** [review]
Let's park this until we agree on specs in https://github.com/ipfs/specs/pull/288.
DoS concerns make this a good candidate for testing RFC process.

@hacdias when writing RFC for that PR, it would be useful to mention the concerns around `.tar.gz` variant  in "Alternatives"  and  "Security" sections.

My hot take is that `.tar` from https://github.com/ipfs/go-ipfs/pull/9029  is fine, but `.tar.gz`  from this PR comes with too much risk, but let's discuss that in ipfs/specs around RFC.

**Comment by lidel** [comment]
Closing as we decided to only do TAR (specs in https://github.com/ipfs/specs/pull/288), which is tracked in https://github.com/ipfs/kubo/pull/9029
(compression can happen at transport layer)

**Pull request closed without merging**
