### PR TITLE
refactor: use gateway from go-libipfs

### PR DESCRIPTION
**Pull request by hacdias**
> Part of https://github.com/ipfs/kubo/issues/8524

This PR is tracking my efforts to isolate the Gateway into a sub-package which will be key to solve #8524. The plan is to first isolate the gateway inside a sub-package that does not depend on anything else from Kubo. After, we can extract it to `go-lipipfs`.

Progress:

- [x] Isolate handlers
- [x] Remove dependencies on:
	- [x] `kubo/tracing` package - might be harder, we may want to instead extract this as a module too.
		- I extracted `tracing.Span` into `spanTrace` inside the gateway subpackage. I think this should be fine as we will still be able to continue to use the tracing functionalities.
	- [x] `kubo/assets` package
		- I also improved the assets package and remove the dependency for NPM.  NPM was simply running a few shell scripts which were now simplified under the `build.sh` file. In addition, I updated the testing script to help visualize both the DAG and the Directory indexes, as well as improved the README.
- [x] Move all unit tests (as possible) that are gateway specific to gateway
- [x] Add a README.md with an example of how it can be run 😃  

TODO:

- [ ] Merge and release https://github.com/ipfs/go-libipfs/pull/65
- [ ] Update dependency here and rebase
- [ ] Merge

cc @lidel for visibility

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel I think I have achieved a very good result here. Everything gateway related is completely extracted into the `gateway` sub-package. I made sure that the gateway package does not depend in any other part of the Kubo base code. You can see my initial comment about it. In addition, I slightly refactored the gateway assets in order to make them easier to work with. I'm happy to receive feedback on this and address it.

We may, or not, merge this PR into Kubo's basecode. Once IPNS is merged to `master`, I will be rebasing this PR. Then, we can either merge this in Kubo and only then perform extraction. Or, I can use this branch as the base for the extraction. it doesn't matter. Either way, this PR allows you to see how the isolated gateway code will look like.

CI: the CI is a bit flaky for unknown reasons to me. In addition the CodeQL CI thingy is flagging things that were already here, but since they were moved, it now thinks they are new issues.

**Review by lidel — COMMENTED** [review]
@hacdias IPNS PRs are in `master` (https://github.com/ipfs/kubo/pull/9399, https://github.com/ipfs/kubo/pull/9471) – feel free to rebase and make any changes to make this ready for final review :pray:

**Comment by hacdias** [comment]
@lidel I opened a PR in `go-libipfs` to add the gateway code there: https://github.com/ipfs/go-libipfs/pull/65

Also updated here to use go-libipfs instead.

**Comment by hacdias** [comment]
@lidel interop is failing bc Cloudflare npm 524.

**Comment by lidel** [comment]
Let's  park this until https://github.com/ipfs/kubo/issues/9579 ships, so it is easier to compare branches.

**Review by lidel — APPROVED** [review]
Reviewed and merged https://github.com/ipfs/go-libipfs/pull/65, this one looks good too.

We should merge this asap so we don't get PRs against old gateway code in this repo.
We can open a separate one for GO interface ajdustments described in https://github.com/ipfs/go-libipfs/issues/61

@hacdias feel free to switch this PR to [the  revision from `main` branch there](https://github.com/ipfs/go-libipfs/commit/a005a50064960ba8258556c8196d01cf1f808e5e) and merge.  :pray:

**Pull request merged**
