### PR TITLE
ci: remove circleci config

### PR DESCRIPTION
**Pull request by galargh**
Here's the comparison between [CircleCI vs GitHub Actions](https://docs.google.com/spreadsheets/d/18B-ZpARJ7ivcKth9uR7G4mvZ_2qT2ypJ0EMFGI1zVOY/edit?usp=sharing). It gives me confidence we can retire CircleCI and embrace GitHub Actions as the main CI provider.

I'm going to resolve conflicts once we're ready to merge because the workflows name changes from this PR affect how workflows show up in GitHub UI/are described by GitHub API so I want to minimise the number of times we're going back and forth on old-new names. 

I'll also merge this - https://github.com/ipfs/github-mgmt/pull/126 - just before merging this.

### CODE REVIEW

**Review by BigLep — COMMENTED** [review]
Awesome - thanks @galargh .  Looks good to me but I'm not close to the specifics.  Will let someone else approve.

**Comment by guseggert** [comment]
Would be nice to have an easy way to find test failures for unit tests, CircleCI has a nice UI for that but I can't find one in GH Actions.

Also is there some similar functionality for finding flaky tests like CircleCI has?

**Comment by guseggert** [comment]
Also can we not merge this until after 0.19 is released? Just so we test another release w/ GH Actions before pulling the trigger.

**Comment by guseggert** [comment]
> Would you need it straight away or could it wait for a little while?

I don't think we "need" it, it'd be nice if we had something similar in GH, as it makes understanding failed tests and managing flakes easier, but we can live without it.

**Comment by galargh** [comment]
> > Would you need it straight away or could it wait for a little while?
> 
> I don't think we "need" it, it'd be nice if we had something similar in GH, as it makes understanding failed tests and managing flakes easier, but we can live without it.

Got it! We will definitely have flaky test reporting - that's on our agenda for this year - and Kubo will surely be one of the first projects where we set it up. I'll keep you posted on this.

Also, if you have any other ideas for what you'd want to see in our CI, don't hesitate to reach out on [#ipdx](https://filecoinproject.slack.com/archives/C03KLC57LKB) 😸

**Comment by guseggert** [comment]
I'm ready to approve but I'm just holding off until 0.19 is released to avoid any mishaps.

**Review by guseggert — APPROVED** [review]

**Pull request merged**
