### PR TITLE
deps: go-merkledag@0.8.1

### PR DESCRIPTION
**Pull request by rvagg**
0.8.0 not yet released, this is testing https://github.com/ipfs/go-merkledag/pull/92 which, if merged, will be 0.8.0. I'm using this to CI test that branch for now but will update if/when we get a tag.

### CODE REVIEW

**Comment by rvagg** [comment]
Updated with release tag: https://github.com/ipfs/go-merkledag/releases/tag/v0.8.0

**Comment by BigLep** [comment]
@Jorropo : can you please review/merge?

**Review by Jorropo — CHANGES_REQUESTED** [review]
@rvagg knows.

**Comment by rvagg** [comment]
yes, he does; and is working on it

**Comment by rvagg** [comment]
ready to go; updated to go-merkledag@v0.8.1, with https://github.com/ipfs/go-merkledag/pull/93

confirmed to deal with https://github.com/ipfs/kubo/issues/9297 even without 773c246232c1f3d7fc67d7ddf5b1cb172ece8fa1 in place

**Review by Jorropo — APPROVED** [review]
LGTM Thx

**Pull request merged**
