### PR TITLE
feat: webui@4.0.1

### PR DESCRIPTION
**Pull request by SgtPooki**
use https://github.com/ipfs/ipfs-webui/releases/tag/v4.0.1

### CODE REVIEW

**Review by hacdias — APPROVED** [review]

**Review by hacdias — CHANGES_REQUESTED** [review]
The interop tests with the Web UI are failing. I upgraded the Node.js version to 18.x which fixed part of the issue. The tests are still not running due to some timeout. Does anyone have an idea?

(Tests are also failing in all commits since IPLD Explorer changes were merged yesterday, so I guess whatever was changed there is related to this.)

**Comment by SgtPooki** [comment]
[interop/ipfs-webui is failing](https://github.com/ipfs/kubo/actions/runs/5255585669/jobs/9495726177?pr=9940) due to playwright timeout when booting up webserver.

```
Run npm run test:e2e

> ipfs-webui@4.0.0 test:e2e
> cross-env REACT_APP_ENV=test npx playwright test -c ./test/e2e

Error: Timed out waiting 60000ms from config.webServer.
```

e2e tests have been starting up and passing fine locally and in ipfs-webui repo.. but i'm looking

**Comment by SgtPooki** [comment]
ok, repro'd locally. weird.

**Comment by SgtPooki** [comment]
should be fixed by https://github.com/ipfs/ipfs-webui/pull/2122

**Review by hacdias — APPROVED** [review]
Thanks for this and for fixing the E2E tests issues!

**Pull request merged**
